export interface TAdata  {
        date: number,
        close_BTC: number,
        volume_BTC: number,
        close_ETH: number,
        volume_ETH: number,
        close_BNB: number,
        volume_BNB: number,
        close_XRP: number,
        volume_XRP: number,
        close: number,
        volume: number,
        ma_5: number,
        ma_6: number,
        ma_10: number,
        ma_20: number,
        rsi_6: number,
        rsi_12: number,
        stochastic_5: number, 
        _kstochastic: number,
        _dstochastic: number,
        macd_hist : number,
        williams_12: number,
        b_bands: number,
        midlle_bands: number
    }